POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Iphone 15",
    "description": "ini handphone merk apple",
    "price": 100,
    "stock": 10
}
### GET PRODUCTS
GET http://localhost:3000/products?limit=2&offset=0
Content-Type: application/json
### GET PRODUCTS BY ID
GET http://localhost:3000/products/2
Content-Type: application/json
### PATCH PRODUCTS BY ID
PATCH http://localhost:3000/products/2
Content-Type: application/json

{
    "price": 2000,
    "stock": 100
}
### DELETE PRODUCTS BY ID 
DELETE http://localhost:3000/products/1
Content-Type: application/json