### CREATE NEW ORDER
POST http://localhost:9000/order
Content-Type: 'application/json

{
    "item": "smart phone",
    "price": 1200
}

### GET DATA ORDER
GET http://localhost:9000/order

### UPDATE DATA ORDER
PATCH http://localhost:9000/order/1
{
    
}

### GET DATA CART
GET http://localhost:9000/cart

### POST DATA CART
POST http://localhost:9000/cart
Content-Type: "application/json"

{
    "item": "smart phone",
    "price": 1200
}